[[datasets]]
resolution = 1024
batch_size = 2

[[datasets.subsets]]
image_dir = "D:\\AIGC\\dataset\\fun\\Anime Pussy\\Pussy Spreading_merge"  # detaset_images
class_tokens = "Anime Pussy"
num_repeats = 2
caption_extension = ".txt"