[[datasets]]
resolution = 1024
batch_size = 1

[[datasets.subsets]]
image_dir = "D:\\AIGC\\dataset\\stegosaurus\\10_stegosaurus"  # detaset_images
class_tokens = "stegosaurus"
num_repeats = 5
caption_extension = ".txt"