[[datasets]]
resolution = 1024
batch_size = 2

[[datasets.subsets]]
image_dir = "D:\\AIGC\\dataset\\fun\\LilyLinglan\\1_LilyLinglan"  # detaset_images
class_tokens = "LilyLinglan"
num_repeats = 2
caption_extension = ".txt"